<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('datacompany')->insert([
            'cpn_name' => 'Gilitransfers',
            'cpn_email' => 'reservation@gilitransfers.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl Gong Kebyar 22 Jimbaran',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://gilitransfers.com',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Angel Billabong',
            'cpn_email' => 'suppliergilitransfers@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Sanur Beach Street Walk, Sanur Kaja, Denpasaraddress_Angel Billabong',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://angelbillabongfastcruise.com',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Arthamas Express',
            'cpn_email' => 'info@arthamasexpress.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Matahari Terbit Sanur, Denpasar, Bali',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://www.arthamasexpress.com/',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Bluewater Express',
            'cpn_email' => 'booking@bluewater-express.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl Tukad Punggawa Br Pojok Serangan',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://bluewater-express.com/',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Caspla Bali Seaview',
            'cpn_email' => 'director@baliseaview.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Pulau Moyo Gang Cemara A No 4 Pedungan Denpasar',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://baliseaview.com/',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => "D'Camel Fast Ferry",
            'cpn_email' => 'reservation@dcamelfastferry.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Hangtuah no. 27 Sanur Denpasar',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://dcamelfastferry.com',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => "D'Prabu",
            'cpn_email' => 'd.prabufastboat@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Gurita No. 22, Br. Pegok Sesetan Denpasar',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Eka Jaya',
            'cpn_email' => 'reservation@baliekajaya.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Setia Budi no 18 Kuta Badung',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://ekajayafastboat.com/',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Gangga Express',
            'cpn_email' => 'suppliergilitransfers@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Br. Tribhuwana, Kusamba, Dawan, Klungkung',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Glory Fast Cruise',
            'cpn_email' => 'booking@gloryfastcruise.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Hangtuah No 27 Sanur, Denpasar',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://www.gloryfastcruise.com/',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Idola Express',
            'cpn_email' => 'info@idolaexpress.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => '-',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://www.idolaexpress.com/',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Maruti Express',
            'cpn_email' => 'rsv@marutigroupfastboat.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Matahari Terbit Arcade 5, Jln. Matahari Terbit, Sanur Kaja, Denpasar',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://marutigroupfastboat.com/',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Ostina',
            'cpn_email' => 'balihappymd@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Pelabuhan Padang Bai, Padangbai, Manggis.',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://www.ostinafastboat.com/',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Semabu Hills',
            'cpn_email' => 'suppliergilitransfers@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Hang Tuah No.27, Sanur, Denpasar',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'The Tanis Express',
            'cpn_email' => 'tanislembongan@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Ruko Arcade, Jl. Matahari Terbit, Sanur Kaja, Denpasar',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://tanisbeachresort.com/',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Wijaya Buyuk',
            'cpn_email' => 'suppliergilitransfers@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Hang Tuah, Sanur, Denpasar',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Gili Getaway',
            'cpn_email' => 'giligetaway@ozemail.com.au',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jln Tukad Punggawa no 25 Serangan Denpasar',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://giligetaway.com',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Rocky Fast Cruise',
            'cpn_email' => 'reservations@rockyfastcruise.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Matahari terbit, Sanur kaja, Denpasar',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://rockyfastcruise.com/',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Golden Queen',
            'cpn_email' => 'booking@goldenqueenfastboat.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. By Pass Ngurah Rai No. 126',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://goldenqueenfastboat.com',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Rayfish Fast Cruise',
            'cpn_email' => 'rayfishfastcruises@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Pantai Matahari Terbit, No.4 Sanur Kaja, Denpasar',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://rayfishfastcruises.com/',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'The Angkal',
            'cpn_email' => 'reservation@theangkalbali.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => '-',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Sekar Jaya',
            'cpn_email' => 'fastboatsekarjaya@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Pasir Putih, Kusamba, Kec. Dawan, Kabupaten Klungkung, Bali',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://sekarjayafastboat.com/',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Bali Hai',
            'cpn_email' => 'reservation@balihaicruises.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Wisata Tirta No.1, Benoa, Denpasar',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://balihaicruises.com/',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Axe Stone Fast Cruise',
            'cpn_email' => 'axestone500@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Sanur Beach Street Walk, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://axestonefastboatbali.com/',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Manta Express',
            'cpn_email' => 'suppliergilitransfers@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jln. Raya Padangbai, 75QH+HPP, padangbai, Kuta, Badung Regency, Bali',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://gilitransfers.com/',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Mahi Mahi Dewata',
            'cpn_email' => 'info@mahimahidewata.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'JL. TUKAD BADUNG NO. 8 B, RENON, BALI',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://mahimahidewata.com/',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Scoot Fast Cruises',
            'cpn_email' => 'rsv@scootcruise.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Hangtuah No.27 Sanur',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'http://scootcruise.com/',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Semaya One Fast Cruise',
            'cpn_email' => 'suppliergilitransfers@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => '-',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Starfish Fast Cruise',
            'cpn_email' => 'starfishfastcruise@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Hang Tuah - Pantai Sanur, BALI',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://starfishfastcruise.com/',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Bali Line Fast Boat',
            'cpn_email' => 'reservation@gilitransfers.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jln. Raya Padangbai',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Invinia Fast Boat',
            'cpn_email' => 'suppliergilitransfers@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Silayukti, Padangbai, Kec. Manggis, Kabupaten Karangasem, Bali 80871',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => "D'Star Fast Ferry",
            'cpn_email' => 'reservation@gilitransfers.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'JL. Matahari Terbit No 03, Sanur Kaja, Denpasar Selatan',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Jaya Fast Boat',
            'cpn_email' => 'suppliergilitransfers@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Setiabudi, Kuta, Kec. Kuta, Kabupaten Badung, Bali 80361',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Dream Beach Express',
            'cpn_email' => 'suppliergilitransfers@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Matahari Terbit No.9A, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali 80228',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'El Rey Fast Cruise',
            'cpn_email' => 'suppliergilitransfers@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Matahari Terbit No.10, Sanur, Denpasar Selatan, Kota Denpasar, Bali 80227',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Marlin',
            'cpn_email' => 'suppliergilitransfers@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Matahari Terbit No.3, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali 80227',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Freebird Express',
            'cpn_email' => 'info@freebird-express.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Raya Amed, Purwakerti, Kec. Abang, Kabupaten Karangasem, Bali 80852',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Inami Luxury',
            'cpn_email' => 'suppliergilitransfers@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Silayukti, Padangbai, Kec. Manggis, Kabupaten Karangasem, Bali 80871',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Wanderlust Fast Boat',
            'cpn_email' => 'reservationwonderlust@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Sedap Malam Gg. Padang Ambuh No.1, Kesiman, Kec. Denpasar Tim., Kota Denpasar, Bali 80237',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Arjuna Fast Cruise',
            'cpn_email' => 'arjunafastcruise9999@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jln. Raya Sanur',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Sunfish Fast Boat',
            'cpn_email' => 'suppliergilitransfers@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jln. Raya Pemelisan',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Ganggari Fast Boat',
            'cpn_email' => 'suppliergilitransfers@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jln. Raya Padangbai',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Wahana virendra',
            'cpn_email' => 'wahanavirendraoffice@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jln. Raya Padangbai',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Karunia Perkasa',
            'cpn_email' => 'suppliergilitransfers@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jln. Raya Padangbai',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Orion Prince',
            'cpn_email' => 'reservation.orionprince@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jln. Raya sedap malam',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'KKB BOAT',
            'cpn_email' => 'suppliergilitransfers@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jln. Raya Bangsal',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Caspla Buyuk',
            'cpn_email' => 'suppliergilitransfers@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Klungkung Nusa Lembongan',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Aman Dia Cruise',
            'cpn_email' => 'info@amandiacruise.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => '-',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Wijaya Perkasa',
            'cpn_email' => 'suppliergilitransfers@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jln raya padangbai',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Sanjaya Fast Boat',
            'cpn_email' => 'suppliergilitransfers@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jlan matahari terbit sanur',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Danayoga Fast Boat',
            'cpn_email' => 'reservation@gilitransfers.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jlan matahari terbit sanur',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Karya Bahari',
            'cpn_email' => 'reservation@gilitransfers.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Lombok harbor',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => "S'Gening Fast Boat",
            'cpn_email' => 'reservation@gilitransfers.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jln. Matahari terbit sanur',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'PUTRA ZAVIER',
            'cpn_email' => 'putrazavier@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'GILI AIR',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'SMILING EXPRESS',
            'cpn_email' => 'reservation@gilitransfers.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jln, raya padangbai',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Karunia Jaya',
            'cpn_email' => 'reservation@gilitransfers.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jln, Raya padangbai',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'EINSTEIN BOAT',
            'cpn_email' => 'reservation@gilitransfers.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jalan Matahari Terbit no 99, Sanur Kaja',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Putri Island Boat',
            'cpn_email' => 'reservation@gilitransfers.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jln. Raya Padangbai',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Gili Gili Fast Boat',
            'cpn_email' => 'reservation@gilitransfers.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jln. Raya Padangbai',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'fast_boat',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Starfish Fast Cruise',
            'cpn_email' => 'starfishfastcruise@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Hang Tuah - Pantai Sanur, BALI',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://starfishfastcruise.com/',
            'cpn_status' => 1,
            'cpn_type' => 'tour',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Bali Hai',
            'cpn_email' => 'reservation@balihaicruises.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Wisata Tirta No.1, Benoa, Denpasar',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://balihaicruises.com/',
            'cpn_status' => 1,
            'cpn_type' => 'tour',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'finns Bali',
            'cpn_email' => 'booking@traviora.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Pantai Berawa, Canggu, Tibubeneng, Kec. Kuta Utara, Kabupaten Badung, Bali 80361',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://balihaicruises.com/',
            'cpn_status' => 1,
            'cpn_type' => 'tour',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Bali Line Fast Boat',
            'cpn_email' => 'reservation@gilitransfers.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jln. Raya Padangbai',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'tour',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Ramayana Ballet Purawisata',
            'cpn_email' => 'booking@traviora.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl. Brigjen Katamso Jl. Ireda, Keparakan, Kec. Mergangsan, Kota Yogyakarta, Daerah Istimewa Yogyakarta 55152',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'tour',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Gilitransfers',
            'cpn_email' => 'reservation@gilitransfers.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => 'Jl Gong Kebyar 22 Jimbaran',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => 'https://gilitransfers.com',
            'cpn_status' => 1,
            'cpn_type' => 'tour',
            'cpn_updated_by' => 1, 
        ]);
        DB::table('datacompany')->insert([
            'cpn_name' => 'Kuber Bali Adventure ATV',
            'cpn_email' => 'kuberbali@gmail.com',
            'cpn_email_status' => 1,
            'cpn_phone' => 6281122223333,
            'cpn_whatsapp' => 6281122223333,
            'cpn_address' => '-',
            'cpn_logo' => "gilitransfers.png",
            'cpn_website' => '-',
            'cpn_status' => 1,
            'cpn_type' => 'tour',
            'cpn_updated_by' => 1, 
        ]);
    }
}
