<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FastBoatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('datafastboat')->insert([
            'fb_company' => 2,
            'fb_name' => 'Angel Billabong',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'angel-billabong-fast-cruise',
            'fb_slug_idn' => 'angel-billabong-fast-cruise',
            'fb_keywords' => 'angel billabong, angel billabong fast boat',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 3,
            'fb_name' => 'Arthamas Express',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'arthamas-express-fast-boat',
            'fb_slug_idn' => 'arthamas-express-fast-boat',
            'fb_keywords' => 'arthamas express, arthamas fast boat, artamas express, artamas lembongan, fast boat lembongan',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 4,
            'fb_name' => 'Bluewater Express',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'bluewater-express',
            'fb_slug_idn' => 'bluewater-express',
            'fb_keywords' => 'bluewater express, bluewater fast boat, bluewater to gili, fast boat bali to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 5,
            'fb_name' => 'Caspla Bali Seaview',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'caspla-bali-seaview',
            'fb_slug_idn' => 'caspla-bali-seaview',
            'fb_keywords' => 'caspla bali sea view, caspla fast boat, caspla bali fast boat, caspla to nusa penida, fast boat to nusa penida',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 6,
            'fb_name' => "D'Camel Fast Ferry",
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'dcamel-fast-ferry',
            'fb_slug_idn' => 'dcamel-fast-ferry',
            'fb_keywords' => 'dcamel fast ferry, dcamel fast boat, dcamel lembongan, fast boat to lembongan',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 9,
            'fb_name' => 'Gangga Express',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'gangga-express',
            'fb_slug_idn' => 'gangga-express',
            'fb_keywords' => 'gangga express fast boat, gangga fast boat, gangga to nusa penida, fast boat to penida, kusamba to nusa penida, gangga express',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 10,
            'fb_name' => 'Glory Fast Cruise',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'glory-fast-cruise',
            'fb_slug_idn' => 'glory-fast-cruise',
            'fb_keywords' => 'glory fast boat, glory fast cruise, fast boat to lembongan, glory to lembongan',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 11,
            'fb_name' => 'Idola Express',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'idola-express',
            'fb_slug_idn' => 'idola-express',
            'fb_keywords' => 'idola express, idola fast boat, idola fast cruise, idola express fast boat, idola boat, fast boat to nusa penida',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 12,
            'fb_name' => 'Maruti Express Fast Boat',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'maruti-express',
            'fb_slug_idn' => 'maruti-express',
            'fb_keywords' => 'maruti rxpress fast boat, maruti fast boat, maruti group fast boat, fast boat to nusa penida, maruti nusa penida',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 13,
            'fb_name' => 'Ostina Fast Boat',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'ostina-fast-boat',
            'fb_slug_idn' => 'ostina-fast-boat',
            'fb_keywords' => 'ostina fast boat, ostina boat, ostina fast boat gili, fast boat bali to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 14,
            'fb_name' => 'Semabu Hills Fast Boat',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'semabu-hills',
            'fb_slug_idn' => 'semabu-hills',
            'fb_keywords' => 'semabu hills, semabu fast boat, semabu fast cruise, semabu to nusa penida, fast boat to nusa penida',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 15,
            'fb_name' => 'The Tanis Express',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'the-tanis-express',
            'fb_slug_idn' => 'the-tanis-express',
            'fb_keywords' => 'tanis lembongan fast boat, tanis express lembongan, the tanis fast boat, tanis express, fast boat tanis, tanis lembongan, sanur to nusa penida, tanis nusa penida',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 16,
            'fb_name' => 'Wijaya Buyuk',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'wijaya-buyuk',
            'fb_slug_idn' => 'wijaya-buyuk',
            'fb_keywords' => 'wijaya buyuk fast boat, wijaya fast boat, wijaya buyuk cruise, fast boat nusa penida',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 17,
            'fb_name' => 'Gili Getaway Fast Boat',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'gili-getaway',
            'fb_slug_idn' => 'gili-getaway',
            'fb_keywords' => 'gili getaway, gili getaway fast boat, gili fast boat, fast boat to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 18,
            'fb_name' => 'Rocky Fast Cruise',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'rocky-fast-cruise',
            'fb_slug_idn' => 'rocky-fast-cruise',
            'fb_keywords' => 'rocky fast cruise, rocky fast boat, rocky lembongan, fast boat rocky, fast boat to lembongan',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 19,
            'fb_name' => 'Golden Queen',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'golden-queen',
            'fb_slug_idn' => 'golden-queen',
            'fb_keywords' => 'golden queen fast boat, golden queen fast cruise, golden queen boat, golden queen gili trawangan, fast boat to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 7,
            'fb_name' => "D'Prabu Fast Boat",
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'dprabu-fast-boat',
            'fb_slug_idn' => 'dprabu-fast-boat',
            'fb_keywords' => 'dprabu fast boat, prabu fast boat, dprabu fast cruise, fast boat to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 8,
            'fb_name' => 'Bali Eka Jaya',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'bali-eka-jaya',
            'fb_slug_idn' => 'bali-eka-jaya',
            'fb_keywords' => 'bali eka jaya, eka jaya fast boat, eka jaya boat',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 20,
            'fb_name' => 'Rayfish Fast Cruises',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'rayfish-fast-cruises',
            'fb_slug_idn' => 'rayfish-fast-cruises',
            'fb_keywords' => 'rayfish fast cruises, rayfish fast boat, rayfish cruise, ray fish fast boat, rayfish nusa penida, fast boat to nusa penida',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 21,
            'fb_name' => 'The Angkal Fast Cruise',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'the-angkal-fast-cruise',
            'fb_slug_idn' => 'the-angkal-fast-cruise',
            'fb_keywords' => 'angkal fast cruise, angkal fast boat, angkal boat kusamba, the angkal fast boat, the angkal fast cruise',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 22,
            'fb_name' => 'Sekar Jaya Fast Boat',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'sekar-jaya-fast-boat',
            'fb_slug_idn' => 'sekar-jaya-fast-boat',
            'fb_keywords' => 'sekar jaya fast boat, sekar jaya boat, kusamba to nusa penida, fast boat to nusa penida',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 24,
            'fb_name' => 'Axe Stone Fast Cruise',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'axe-stone-fast-cruise',
            'fb_slug_idn' => 'axe-stone-fast-cruise',
            'fb_keywords' => 'axe stone fast boat, axe stone fast cuise, axe stone bali to penida, fast boat bali to nusa penida',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 25,
            'fb_name' => 'Manta Express Fast Boat',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'manta-express-fast-boat',
            'fb_slug_idn' => 'manta-express-fast-boat',
            'fb_keywords' => 'manta express fast boat, manta fast boat, manta boat, fast boat manta, manta bali to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 26,
            'fb_name' => 'Mahi Mahi Dewata',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'mahi-mahi-dewata',
            'fb_slug_idn' => 'mahi-mahi-dewata',
            'fb_keywords' => 'mahi mahi dewata, mahi mahi fast boat, mahi mahi boat, mahi dewata fast boat',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 27,
            'fb_name' => 'Scoot Fast Cruises',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'scoot-fast-cruises',
            'fb_slug_idn' => 'scoot-fast-cruises',
            'fb_keywords' => 'scoot fast cruise, scoot fast boat, scoot sanur, fast boat sanur to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 28,
            'fb_name' => 'Semaya One Fast Cruise',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'semaya-one-fast-cruise',
            'fb_slug_idn' => 'semaya-one-fast-cruise',
            'fb_keywords' => 'semaya one, semaya fast boat, semaya one fast boat, semaya one fast cruise, semaya fast cruise, fast boat bali to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 29,
            'fb_name' => 'Starfish Fast Cruise',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'starfish-fast-cruise',
            'fb_slug_idn' => 'starfish-fast-cruise',
            'fb_keywords' => 'starfish fast boat, starfish fast cruise, starfish cruise, fast boat starfish, fast boat bali to nusa penida, gili trawangan to nusa penida',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 32,
            'fb_name' => "D'Stars Fast Ferry",
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'dstars-fast-ferry-lembongan',
            'fb_slug_idn' => 'dstars-fast-ferry-lembongan',
            'fb_keywords' => 'dstars fast ferry, stars fast boat, dstars fast boat, dstars ferry lembongan',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 30,
            'fb_name' => 'Bali Line Fast Boat',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'bali-line-fast-boat',
            'fb_slug_idn' => 'bali-line-fast-boat',
            'fb_keywords' => 'bali line fast boat, bali line cruise, bali line fast cruise, fast boat from serangan, fast boat bali to nusa penida',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 37,
            'fb_name' => 'Freebird Express Fast Boat',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'freebird-express-fastboat',
            'fb_slug_idn' => 'freebird-express-fastboat',
            'fb_keywords' => 'freebird express, freebird fast boat, freebird amed, fast boat amed to gili, amed to gili, freebird fast ferry, freebird fast cruise',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 35,
            'fb_name' => 'El Rey Fast Cruise',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'el-rey-fast-cruise',
            'fb_slug_idn' => 'el-rey-fast-cruise',
            'fb_keywords' => 'el rey fast cruise, el rey fast boat, el rey fast ferry, el rey nusa penida, fast boat to nusa penida',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 36,
            'fb_name' => 'Marlin Fast Boat',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'marlin-fast-boat',
            'fb_slug_idn' => 'marlin-fast-boat',
            'fb_keywords' => 'marlin fast boat, marlin fast cruise, marlin fast ferry, marlin ferry nusa lembongan, marlin nusa lembongan, fast boat to nusa lembongan',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 34,
            'fb_name' => 'Dream Beach Express',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'dream-beach-express',
            'fb_slug_idn' => 'dream-beach-express',
            'fb_keywords' => 'dream beach fast boat, dream beach express, dream beach fast ferry, dream beach fast cruise, dream beach nusa lembongan',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 38,
            'fb_name' => 'Inami Luxury Fast Boat',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'inami-luxury-fast-boat',
            'fb_slug_idn' => 'inami-luxury-fast-boat',
            'fb_keywords' => 'inami luxury fast boat, inami luxury fast cruise, inami fast boat, inami fast ferry, fast boat penida to gili, fast boat bali to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 39,
            'fb_name' => 'Wanderlust Cruise',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'wanderlust-cruise',
            'fb_slug_idn' => 'wanderlust-cruise',
            'fb_keywords' => 'wanderlust cruise, wanderlust fast boat, wanderlust fast cruise, cruise bali to gili, fast boat bali to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 28,
            'fb_name' => 'Semaya One  Shuttle Bus',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'semaya-one-with-shuttle-bus',
            'fb_slug_idn' => 'semaya-one-with-shuttle-bus',
            'fb_keywords' => 'semaya one, semaya fast boat, semaya one fast boat, semaya one fast cruise, semaya fast cruise, fast boat bali to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 28,
            'fb_name' => 'Semaya One  Private Car ',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'semaya-one-with-private-car',
            'fb_slug_idn' => 'semaya-one-with-private-car',
            'fb_keywords' => 'semaya one, semaya fast boat, semaya one fast boat, semaya one fast cruise, semaya fast cruise, fast boat bali to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 19,
            'fb_name' => 'Golden Queen with Private Car',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'golden-queen-with-private-car',
            'fb_slug_idn' => 'golden-queen-with-private-car',
            'fb_keywords' => 'golden queen fast boat, golden queen fast cruise, golden queen boat, golden queen gili trawangan, fast boat to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 38,
            'fb_name' => 'Inami  Private Car ',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'inami-luxury-with-private-car',
            'fb_slug_idn' => 'inami-luxury-with-private-car',
            'fb_keywords' => 'inami luxury fast boat, inami luxury fast cruise, inami fast boat, inami fast ferry, fast boat penida to gili, fast boat bali to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 25,
            'fb_name' => 'Manta Express  Private Car',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'manta-express-with-private-car',
            'fb_slug_idn' => 'manta-express-with-private-car',
            'fb_keywords' => 'manta express fast boat, manta fast boat, manta boat, fast boat manta, manta bali to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 38,
            'fb_name' => 'Inami Luxury with Shuttle Bus',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'inami-with-shuttle-bus',
            'fb_slug_idn' => 'inami-with-shuttle-bus',
            'fb_keywords' => 'inami luxury fast boat, inami luxury fast cruise, inami fast boat, inami fast ferry, fast boat penida to gili, fast boat bali to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 25,
            'fb_name' => 'Manta Express  Shuttle Bus',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'manta-express-with-shuttle-bus',
            'fb_slug_idn' => 'manta-express-with-shuttle-bus',
            'fb_keywords' => 'manta express fast boat, manta fast boat, manta boat, fast boat manta, manta bali to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 19,
            'fb_name' => 'Golden Queen with Shuttle Bus',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'golden-queen-with-shuttle-bus',
            'fb_slug_idn' => 'golden-queen-with-shuttle-bus',
            'fb_keywords' => 'golden queen fast boat, golden queen fast cruise, golden queen boat, golden queen gili trawangan, fast boat to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 40,
            'fb_name' => 'Arjuna Fast Cruise',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'arjuna-fast-cruise',
            'fb_slug_idn' => 'arjuna-fast-cruise',
            'fb_keywords' => 'arjuna fast boat, arjuna fast cruise, arjuna fast ferry, arjuna fast boat penida, fast boat to nusa penida, fast boat bali to nusa penida',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 41,
            'fb_name' => 'Sunfish Fast Boat',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'sunfish-fast-boat',
            'fb_slug_idn' => 'sunfish-fast-boat',
            'fb_keywords' => 'sunfish fast boat, sunfish boat, fast boat to gili, fast boat bali to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 31,
            'fb_name' => 'Invinia Fast Boat',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'invinia-fast-boat',
            'fb_slug_idn' => 'invinia-fast-boat',
            'fb_keywords' => 'invinia fast boat, invinia fast cruise, invinia bali to gili, fast boat bali to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 31,
            'fb_name' => 'Invinia  Private Car ',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'invinia-fast-boat-with-private-car',
            'fb_slug_idn' => 'invinia-fast-boat-with-private-car',
            'fb_keywords' => 'invinia fast boat, shuttle car padangbai, fast boat with shuttle, invinia with shuttle',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 31,
            'fb_name' => 'Invinia  Shuttle Bus',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'invinia-fast-boat-with-shuttle-bus',
            'fb_slug_idn' => 'invinia-fast-boat-with-shuttle-bus',
            'fb_keywords' => 'invinia fast boat, invinia fast cruise, invinia bali to gili, fast boat bali to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 15,
            'fb_name' => 'The Tanis with Transport',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'tanis-with-transport',
            'fb_slug_idn' => 'tanis-with-transport',
            'fb_keywords' => 'tanis lembongan fast boat, tanis express lembongan, the tanis fast boat, tanis express, fast boat tanis, tanis lembongan',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 35,
            'fb_name' => 'El Rey With Transport',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'el-rey-with-transport',
            'fb_slug_idn' => 'el-rey-with-transport',
            'fb_keywords' => 'el rey fast cruise, el rey fast boat, el rey fast ferry, el rey nusa penida, fast boat to nusa penida',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 24,
            'fb_name' => 'Axe Stone With Transport',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'axe-stone-with-transport',
            'fb_slug_idn' => 'axe-stone-with-transport',
            'fb_keywords' => 'axe stone fast boat, axe stone fast cuise, axe stone bali to penida, fast boat bali to nusa penida',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 11,
            'fb_name' => 'Idola with Transport',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'idola-with-transport',
            'fb_slug_idn' => 'idola-with-transport',
            'fb_keywords' => 'idola express, idola fast boat, idola fast cruise, idola express fast boat, idola boat, fast boat to nusa penida',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 42,
            'fb_name' => 'New Ganggari',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'ganggari-fast-boat',
            'fb_slug_idn' => 'ganggari-fast-boat',
            'fb_keywords' => 'ganggari, bali to gili, fast boat bali, ganggari fast boat, bali fast boat, gili trawangan to bali ',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 43,
            'fb_name' => 'Wahana Virendra',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'wahana-virendra-fast-boat',
            'fb_slug_idn' => 'wahana-virendra-fast-boat',
            'fb_keywords' => 'wahana fast boat, wahana virendra, bali to gili fast boat',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 44,
            'fb_name' => 'Karunia Perkasa',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'karunia-perkasa-fast-boat',
            'fb_slug_idn' => 'karunia-perkasa-fast-boat',
            'fb_keywords' => 'karunia perkasa, wijaya perkasa, fast boat bali, fast boat gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 45,
            'fb_name' => 'Orion Prince Fast Boat',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'orion-fast-boat',
            'fb_slug_idn' => 'orion-fast-boat',
            'fb_keywords' => 'orion prince, fast boat gili, bali to gili, kapal cepat bali, gili trawangan, serangan to gili trawangan',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 46,
            'fb_name' => 'KKB fast boat',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'kkb-fast-boat',
            'fb_slug_idn' => 'kkb-fast-boat',
            'fb_keywords' => 'inter island fast boat, gili trawangan to gili air, bangsal to gili meno',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 47,
            'fb_name' => 'Caspla Buyuk',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'caspla-buyuk-fast-boat',
            'fb_slug_idn' => 'caspla-buyuk-fast-boat',
            'fb_keywords' => 'caspla, fast boat bali, caspla buyuk',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 48,
            'fb_name' => 'Aman Dia Cruise ',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'aman-dia-cruise-bali',
            'fb_slug_idn' => 'aman-dia-cruise-bali',
            'fb_keywords' => 'fast boat bali, aman dia cruise, bali to nusa penida, fast boat nusa penida, ',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 49,
            'fb_name' => 'Wijaya Perkasa Fast Boat',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'wijaya-perkasa-fast-boat',
            'fb_slug_idn' => 'wijaya-perkasa-fast-boat',
            'fb_keywords' => 'fast boat bali, bali to gili, wijaya perkasa, gili trawangan to bali, wijaya fast boat ',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 49,
            'fb_name' => 'Wijaya Perkasa with Shuttle ',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'wijaya-perkasa-with-shuttle',
            'fb_slug_idn' => 'wijaya-perkasa-with-shuttle',
            'fb_keywords' => 'fast boat bali, bali to gili, wijaya perkasa, gili trawangan to bali, wijaya fast boat ',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 49,
            'fb_name' => 'Wijaya Perkasa with Private Car',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'wijaya-perkasa-with-private-car',
            'fb_slug_idn' => 'wijaya-perkasa-with-private-car',
            'fb_keywords' => 'wijaya perkasa fast boat, bali to gili, gili trawangan to bali, wijaya fast boat',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 50,
            'fb_name' => 'Sanjaya Fast Boat',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'sanjaya-fast-boat',
            'fb_slug_idn' => 'sanjaya-fast-boat',
            'fb_keywords' => 'sanjaya fast boat, bali to nusa penida, fast boat nusa penida, sanur to penida, fast boat from sanur',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 51,
            'fb_name' => 'Danayoga Fast Boat',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'danayoga-fast-boat',
            'fb_slug_idn' => 'danayoga-fast-boat',
            'fb_keywords' => 'Dana yoga',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 52,
            'fb_name' => 'Karya Bahari Fast Boat Gili',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'karya-bahari-fast-boat-gili',
            'fb_slug_idn' => 'karya-bahari-fast-boat-gili',
            'fb_keywords' => 'karya bahari, fast boat gili lombok, gili to lombok, gili trawangan to gili meno',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 53,
            'fb_name' => "S'Gening Fast Boat",
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'sgening-fast-boat',
            'fb_slug_idn' => 'sgening-fast-boat',
            'fb_keywords' => 'Sgening Fast boat',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 54,
            'fb_name' => 'Putra Zavier - Inter Island Boat Gili',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'putra-zavier-inter-island-boat',
            'fb_slug_idn' => 'putra-zavier-inter-island-boat',
            'fb_keywords' => 'gili trawangan to bangsal, gili to lombok, gili air to bangsal, gili trawangan boat ',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 55,
            'fb_name' => 'SMILING EXPRESS FAST BOAT',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'smiling-express-fast-boat',
            'fb_slug_idn' => 'smiling-express-fast-boat',
            'fb_keywords' => 'bali to gili, bali to lombok, padangbai to gili, padangbai to lombok, gili to padangbai',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 56,
            'fb_name' => 'Karunia Jaya Fast Boat',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'karunia-jaya-fast-boat',
            'fb_slug_idn' => 'karunia-jaya-fast-boat',
            'fb_keywords' => 'karunia-jaya-fast-boat',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 57,
            'fb_name' => 'EINSTEIN BOAT',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'einstein-fast-boat',
            'fb_slug_idn' => 'einstein-fast-boat',
            'fb_keywords' => 'einstein-fast-boat',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 44,
            'fb_name' => 'Karunia Perkasa with Shuttle ',
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'karunia-perkasa-fast-boat-with-shuttle',
            'fb_slug_idn' => 'karunia-perkasa-fast-boat-with-shuttle',
            'fb_keywords' => 'karunia perkasa, wijaya perkasa, fast boat bali, fast boat gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 44,
            'fb_name' => "Karunia Perkasa with Private Car ",
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'karunia-perkasa-fast-boat-with-private-car',
            'fb_slug_idn' => 'karunia-perkasa-fast-boat-with-private-car',
            'fb_keywords' => 'karunia perkasa, wijaya perkasa, fast boat bali, fast boat gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 56,
            'fb_name' => "Karunia Jaya Fast Boat with Shuttle Bus",
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'karunia-jaya-fast-boat-with-shuttle',
            'fb_slug_idn' => 'karunia-jaya-fast-boat-with-shuttle',
            'fb_keywords' => 'karunia jaya, karunia jaya fast boat, padangbai to gili ',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 56,
            'fb_name' => "Karunia Jaya Fast Boat with Private Car",
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'karunia-jaya-fast-boat-with-private-car',
            'fb_slug_idn' => 'karunia-jaya-fast-boat-with-private-car',
            'fb_keywords' => 'karunia jaya, karunia jaya fast boat, padangbai to gili ',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 43,
            'fb_name' => "Wahana Virendra with Shuttle Bus",
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'wahana-virendra-fast-boat-with-shuttle',
            'fb_slug_idn' => 'wahana-virendra-fast-boat-with-shuttle',
            'fb_keywords' => 'wahana fast boat, wahana virendra, bali to gili fast boat',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 43,
            'fb_name' => "Wahana Virendra with Private Car",
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'wahana-virendra-fast-boat-with-private-car',
            'fb_slug_idn' => 'wahana-virendra-fast-boat-with-private-car',
            'fb_keywords' => 'wahana fast boat, wahana virendra, bali to gili fast boat',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 59,
            'fb_name' => "Gili Gili Fast Boat",
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'gili-gili-fast-boat',
            'fb_slug_idn' => 'gili-gili-fast-boat',
            'fb_keywords' => 'gili gili fast boat, fast boat padangbai, bali to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
        DB::table('datafastboat')->insert([
            'fb_company' => 58,
            'fb_name' => "PUTRI ISLAND FAST BOAT",
            'fb_image1' => 'gilitransfer.png',
            'fb_image2' => 'gilitransfer.png',
            'fb_image3' => 'gilitransfer.png',
            'fb_slug_en' => 'putri-island-fast-boat',
            'fb_slug_idn' => 'putri-island-fast-boat',
            'fb_keywords' => 'putri island fast boat, padangbai to gili, bali to gili',
            'fb_description_en' => '-',
            'fb_description_idn' => '-',
            'fb_content_en' => '-',
            'fb_content_idn' => '-',
            'fb_updated_by' => 1,
        ]);
    }
}
