<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PortSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('masterport')->insert([
            'prt_island' => 1,
            'prt_name_en' => 'Amed Port',
            'prt_name_idn' => 'Pelabuhan Amed',
            'prt_address' => 'Jl. Raya Amed, Purwakerti, Kec. Abang, Kabupaten Karangasem, Bali 80852',
            'prt_code' => 'AMDP', 
            'prt_slug_en' => 'amed-port',
            'prt_slug_idn' => 'amed-port',
            'prt_keyword' => 'amed port, amed harbor, amed harbour, pelabuhan amed',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.337892152061137, 115.65988695723367',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
        DB::table('masterport')->insert([
            'prt_island' => 5,
            'prt_name_en' => 'Bangsal Harbor',
            'prt_name_idn' => 'Pelabuhan Bangsal',
            'prt_address' => 'J34X+FQ West Pemenang, North Lombok Regency, West Nusa Tenggara',
            'prt_code' => 'BNSP', 
            'prt_slug_en' => 'bangsal-harbor',
            'prt_slug_idn' => 'bangsal-harbor',
            'prt_keyword' => 'bangsal port, bangsal harbor, bangsal, pelabuhan bangsal',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.393709110551585, 116.09937333066998',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
        DB::table('masterport')->insert([
            'prt_island' => 7,
            'prt_name_en' => 'Buyuk Harbour',
            'prt_name_idn' => 'Pelabuhan Buyuk',
            'prt_address' => 'Jl. Nusa Indah No.53, Kutampi Kaler, Kec. Nusa Penida, Kabupaten Klungkung, Bali 80771',
            'prt_code' => 'BYKP', 
            'prt_slug_en' => 'buyuk-harbour',
            'prt_slug_idn' => 'buyuk-harbour',
            'prt_keyword' => 'buyuk, buyuk port, buyuk harbor, buyuk nusa penida',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.673648609410986, 115.54658901350625',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
        DB::table('masterport')->insert([
            'prt_island' => 1,
            'prt_name_en' => 'Banjar Nyuh Port',
            'prt_name_idn' => 'Pelabuhan Banjar Nyuh',
            'prt_address' => 'Ped, Nusa Penida, Klungkung Regency, Bali 80771',
            'prt_code' => 'BJNP', 
            'prt_slug_en' => 'banjar-nyuh-port',
            'prt_slug_idn' => 'banjar-nyuh-port',
            'prt_keyword' => 'banjar nyuh, banjar nyuh nusa penida, banjar nyuh harbor, banjar nyuh port, dermaga banjar nyuh',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.677953271512482, 115.48848678654973',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
        DB::table('masterport')->insert([
            'prt_island' => 1,
            'prt_name_en' => 'Port of Benoa',
            'prt_name_idn' => 'Pelabuhan Benoa',
            'prt_address' => 'Jalan Dermaga II, Pedungan, Kuta Selatan, Kota Denpasar, Bali',
            'prt_code' => 'BNOP', 
            'prt_slug_en' => 'benoa-port',
            'prt_slug_idn' => 'benoa-port',
            'prt_keyword' => 'benoa harbor, benoa port, benoa harbour, pelabuhan benoa',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.740350053942844, 115.21166384646199',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
        DB::table('masterport')->insert([
            'prt_island' => 3,
            'prt_name_en' => 'Gili Meno Port',
            'prt_name_idn' => 'Pelabuhan Gili Meno',
            'prt_address' => 'J3X6+2P Gili Indah, North Lombok Regency, West Nusa Tenggara',
            'prt_code' => 'GLMP', 
            'prt_slug_en' => 'gili-meno-port',
            'prt_slug_idn' => 'gili-meno-port',
            'prt_keyword' => 'gili meno, gili meno port, gili meno harbor, pelabuhan gili meno',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.352183084123148, 116.061790457671',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
        DB::table('masterport')->insert([
            'prt_island' => 2,
            'prt_name_en' => 'Gili Air Port',
            'prt_name_idn' => 'Pelabuhan Gili Air',
            'prt_address' => 'J3PM+G6H, Gili Indah, Kec. Pemenang, Kabupaten Lombok Utara, Nusa Tenggara Bar. 83352',
            'prt_code' => 'GLAP', 
            'prt_slug_en' => 'gili-air-port',
            'prt_slug_idn' => 'gili-air-port',
            'prt_keyword' => 'gili air, gili air port, pelabuhan gili air, gili air harbor',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.363458384552061, 116.08310136758803',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
        DB::table('masterport')->insert([
            'prt_island' => 4,
            'prt_name_en' => 'Gili Trawangan Port',
            'prt_name_idn' => 'Pelabuhan Gili Trawangan',
            'prt_address' => 'J2WV+RF2, Gili Trawangan, Gili Indah, Kec. Pemenang, Kabupaten Lombok Utara, Nusa Tenggara Bar. 8335',
            'prt_code' => 'GLTP', 
            'prt_slug_en' => 'gili-trawangan-port',
            'prt_slug_idn' => 'gili-trawangan-port',
            'prt_keyword' => 'gili trawangan, gili trawangan port, gili trawangan harbor, pelabuhan gili trawangan',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.355138991522299, 116.04353132418325',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
        DB::table('masterport')->insert([
            'prt_island' => 6,
            'prt_name_en' => 'Jungut Batu Port',
            'prt_name_idn' => 'Pelabuhan Jungut Batu',
            'prt_address' => 'nusa lembongan, Jungutbatu, Kec. Nusa Penida, Kabupaten Klungkung, Bali 80224',
            'prt_code' => 'JNBP', 
            'prt_slug_en' => 'jungut-batu-port',
            'prt_slug_idn' => 'jungut-batu-port',
            'prt_keyword' => 'jungut batu port, jungut batu, jungut batu lembongan, pelabuhan jungut batu',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.676395844711319, 115.4468133154972',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
        DB::table('masterport')->insert([
            'prt_island' => 5,
            'prt_name_en' => 'Lembar Harbour',
            'prt_name_idn' => 'Pelabuhan Lembar',
            'prt_address' => 'Jl. Raya Pelabuhan No. 5, Lembar, Lombok Barat, Nusa Tenggara Barat - 83364',
            'prt_code' => 'LMBP', 
            'prt_slug_en' => 'lembar-harbour',
            'prt_slug_idn' => 'lembar-harbour',
            'prt_keyword' => 'lembar harbor, lembar harbour, lembar port, lembar, pelabuhan lembar',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.729878019938216, 116.07706630688293',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
        DB::table('masterport')->insert([
            'prt_island' => 6,
            'prt_name_en' => 'Mushroom Bay Port',
            'prt_name_idn' => 'Pelabuhan Mushroom Bay',
            'prt_address' => 'Mushroom beach port, Mushroom Beach Road, Jungutbatu, Kec. Nusa Penida, Kabupaten Klungkung, Bali 80',
            'prt_code' => 'MSBP', 
            'prt_slug_en' => 'mushroom-bay-port',
            'prt_slug_idn' => 'mushroom-bay-port',
            'prt_keyword' => 'mushroom bay, mushroom bay lembongan, mushroom bay port, dermaga mushroom bay ',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.682991960927133, 115.43303949893084',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
        DB::table('masterport')->insert([
            'prt_island' => 1,
            'prt_name_en' => 'Padangbai Harbor',
            'prt_name_idn' => 'Pelabuhan Padangbai',
            'prt_address' => 'Padangbai, Manggis, Kec. Karangasem, Bali',
            'prt_code' => 'PDBP', 
            'prt_slug_en' => 'padangbai-harbour',
            'prt_slug_idn' => 'padangbai-harbour',
            'prt_keyword' => 'padangbai harbor, padangbai port, port of padangbai, padangbai, padangbai harbour',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.533081876161683, 115.50832214558814',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
        DB::table('masterport')->insert([
            'prt_island' => 7,
            'prt_name_en' => 'Sampalan Port',
            'prt_name_idn' => 'Pelabuhan Sampalan',
            'prt_address' => 'Batununggul, Nusa Penida, Klungkung Regency, Bali 80771',
            'prt_code' => 'SMLP', 
            'prt_slug_en' => 'sampalan-port',
            'prt_slug_idn' => 'sampalan-port',
            'prt_keyword' => 'sampalan, sampalan port, sampalan harbor, dermaga sampalan, sampalan nusa penida',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.655108772282915, 115.55847230502522',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
        DB::table('masterport')->insert([
            'prt_island' => 1,
            'prt_name_en' => 'Sanur Port',
            'prt_name_idn' => 'Pelabuhan Sanur',
            'prt_address' => '87J6+4CG, Jl.Pantai Matahari Terbit, Sanur Kaja, Denpasar Selatan, Kota Denpasar, Bali 80237',
            'prt_code' => 'SNRP', 
            'prt_slug_en' => 'sanur-port',
            'prt_slug_idn' => 'sanur-port',
            'prt_keyword' => 'sanur, sanur port, port of fast boat, sanur harbor',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.669471568793748, 115.26107159642628',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
        DB::table('masterport')->insert([
            'prt_island' => 5,
            'prt_name_en' => 'Senggigi Port',
            'prt_name_idn' => 'Pelabuhan Senggigi',
            'prt_address' => 'Senggigi, Batu Layar, West Lombok Regency, West Nusa Tenggara',
            'prt_code' => 'SNGP', 
            'prt_slug_en' => 'senggigi-port',
            'prt_slug_idn' => 'senggigi-port',
            'prt_keyword' => 'senggigi port, senggigi, dermaga senggigi',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.478695375023847, 116.03761619267462',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
        DB::table('masterport')->insert([
            'prt_island' => 1,
            'prt_name_en' => 'Serangan Harbor',
            'prt_name_idn' => 'Pelabuhan Serangan',
            'prt_address' => 'Jl. Tukad Punggawa, Serangan, Denpasar Selatan, Denpasar City, Bali 80229',
            'prt_code' => 'SRGP', 
            'prt_slug_en' => 'serangan-harbor',
            'prt_slug_idn' => 'serangan-harbor',
            'prt_keyword' => 'serangan, serangan port, serangan harbor, pelabuhan serangan',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.72125792198133, 115.23897158293329',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
        DB::table('masterport')->insert([
            'prt_island' => 7,
            'prt_name_en' => 'Toyapakeh Port',
            'prt_name_idn' => 'Pelabuhan Toyapakeh',
            'prt_address' => 'Kp. Toyapakeh, Kec. Nusa Penida, Kabupaten Klungkung, Bali',
            'prt_code' => 'TPHP', 
            'prt_slug_en' => 'toyapakeh-port',
            'prt_slug_idn' => 'toyapakeh-port',
            'prt_keyword' => 'toyapakeh, toyapakeh port, toyapakeh harbor, dermaga toyapakeh',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.682331523118501, 115.48682204300671',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
        DB::table('masterport')->insert([
            'prt_island' => 1,
            'prt_name_en' => 'Kusamba Port',
            'prt_name_idn' => 'Pelabuhan Kusamba',
            'prt_address' => 'CFP3+57C, Kp. Kusamba, Kec. Dawan, Kabupaten Klungkung, Bali',
            'prt_code' => 'KSBP', 
            'prt_slug_en' => 'kusamba-port',
            'prt_slug_idn' => 'kusamba-port',
            'prt_keyword' => 'kusamba, kusamba port, gangga port, kusamba harbor, pelabuhan kusamba',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.564545791716911, 115.45312755163704',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
        DB::table('masterport')->insert([
            'prt_island' => 7,
            'prt_name_en' => 'Kutampi Port',
            'prt_name_idn' => 'Pelabuhan Kutampi',
            'prt_address' => 'Jl. Pantai, Kutampi, Kec. Nusa Penida, Kabupaten Klungkung, Bali 80771',
            'prt_code' => 'KTMP', 
            'prt_slug_en' => 'kutampi-port',
            'prt_slug_idn' => 'kutampi-port',
            'prt_keyword' => 'kutampi, kutampi port, dermaga kutampi, kutampi nusa penida',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.672090415140973, 115.5514864539959',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
        DB::table('masterport')->insert([
            'prt_island' => 6,
            'prt_name_en' => 'Yellow Bridge',
            'prt_name_idn' => 'Yellow Bridge Lembongan',
            'prt_address' => 'Jl. Yellow Bridge, Lembongan, Kec. Nusa Penida, Kabupaten Klungkung, Bali 80771',
            'prt_code' => 'YBP', 
            'prt_slug_en' => 'yellow-bridge-port',
            'prt_slug_idn' => 'yellow-bridge-port',
            'prt_keyword' => 'yellow bridge, yellow bridge lembongan, yellow bridge port, pelabuhan nusa lembongan',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.694178917533018, 115.45098419563489',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
        DB::table('masterport')->insert([
            'prt_island' => 1,
            'prt_name_en' => 'Pemelisan Port',
            'prt_name_idn' => 'Pelabuhan Pemelisan',
            'prt_address' => '76MH+V7R, Jl. Pemelisan 1, Sesetan, Denpasar Selatan, Kota Denpasar, Bali',
            'prt_code' => 'PML', 
            'prt_slug_en' => 'pemelisan-port',
            'prt_slug_idn' => 'pemelisan-port',
            'prt_keyword' => 'pemelisan, pemelisan port, pemelisan harbor, pelabuhan pemelisan',
            'prt_image1' => 'gilitransfers.png',
            'prt_image2' =>'gilitransfers.png',
            'prt_image3' => 'gilitransfers.png',
            'prt_map' => '-8.71520349621782, 115.22812206595327',
            'prt_description_en' => '-',
            'prt_description_idn' => '-',
            'prt_content_en' => '-',
            'prt_content_idn' => '-',
            'prt_updated_by' => 1,
        ]);
    }
}
